// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWCJK0s9jcjnif0mAY4xb9UUnBgWVna0',
    appId: '1:367405142252:web:acbdb715189207876b95c9',
    messagingSenderId: '367405142252',
    projectId: 'fintrack-7e821',
    authDomain: 'fintrack-7e821.firebaseapp.com',
    storageBucket: 'fintrack-7e821.firebasestorage.app',
    measurementId: 'G-YXMY4QR428',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClR8GcbIENQtHw2hN3prjeWYMYvV-R6e4',
    appId: '1:367405142252:android:cfe8729ec7df04796b95c9',
    messagingSenderId: '367405142252',
    projectId: 'fintrack-7e821',
    storageBucket: 'fintrack-7e821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNk4m-cV-u3L2isuiGabyCguzcfYHIzw',
    appId: '1:367405142252:ios:1330847a81bce62a6b95c9',
    messagingSenderId: '367405142252',
    projectId: 'fintrack-7e821',
    storageBucket: 'fintrack-7e821.firebasestorage.app',
    iosBundleId: 'fast.com.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOWCJK0s9jcjnif0mAY4xb9UUnBgWVna0',
    appId: '1:367405142252:web:01c861efa8e96e936b95c9',
    messagingSenderId: '367405142252',
    projectId: 'fintrack-7e821',
    authDomain: 'fintrack-7e821.firebaseapp.com',
    storageBucket: 'fintrack-7e821.firebasestorage.app',
    measurementId: 'G-70VJY12GKH',
  );
}
